### ISSUE TITLE
최초 설치시에 Please install afox가 나옵니다.

### ISSUE THREAD

**Issue by KoreaFramework** [phiDelPark/aFox#1]
localhost/install/index.php를 들어가면 설치화면이 나오는데 DB정보를 입력해도 Please install afox가 나오면서 설치가 안됩니다.

수정중일수도 있을것같아서 쓰지않으려고 했는데 혹시나해서 적어둡니다.

**Comment by KoreaFramework** [comment]
form action이 ./로 되있어서 index.php로 수정해서 설치했습니다.
action이 ./로 되있어서 install 폴더로 넘어가서 폼값이 전송되네요.

**Comment by phiDelPark** [comment]
감사합니다.^^
